---

- hosts: node2
  remote_user: root
  vars:
    project_name: AccountOnline2
    remote_nginx_enable_dir: /etc/nginx/sites-enabled
    remote_nginx_avail_dir: /etc/nginx/sites-available
    local_config_dir: ./deployconfig

  tasks:
    - name: stop nginx
      systemd: name=nginx state=stopped

    - name: remove nginx enable project symlink
      file: name={{ remote_nginx_enable_dir }}/my_site.conf state=absent

    - name: remove nginx avaliable project config file
      file: name={{ remote_nginx_avail_dir }}/my_site.conf state=absent

    - name: copy nginx project config file
      copy: src={{ local_config_dir }}/nginx.conf dest={{ remote_nginx_avail_dir }}/my_site.conf

    - name: create symlink
      file: src={{ remote_nginx_avail_dir }}/my_site.conf dest={{ remote_nginx_enable_dir }}/my_site.conf state=link

    - name: restart nginx
      systemd: name=nginx state=restarted
