---

- hosts: node2
  remote_user: root
  vars_files:
    - vars.yml

  tasks:
    - name: apt-get update
      apt: update_cache=yes
      sudo: yes

    - name: install nginx
      apt: name=nginx state=present

    - name: install supervisor
      apt: name=supervisor state=present

    - name: remove website dir
      file: name={{ remote_app_dir }}/{{ project_name }} state=absent

    - name: create app dir
      file: name={{ remote_app_dir }} state=directory

    - name: change mode of app dir
      file: name={{ remote_app_dir }} mode=777 recurse=yes

    - name: create website dir
      file: name={{ remote_app_dir }}/{{ project_name }} state=directory

    - name: create logs dir
      file: name={{ remote_app_dir }}/{{ project_name }}/logs state=directory

    - name: create tool dir
      file: name={{ remote_app_dir }}/{{ project_name }}/tool state=directory
