---
# tasks file for server

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
    - python3
    - python3-pip
    - python3-setuptools
    - nginx
    - supervisor
  sudo: yes
