---

- hosts: node2
  remote_user: root
  vars_files:
    - vars.yml

  tasks:
    - name: stop nginx
      systemd: name=nginx state=stopped

    - name: remove nginx enable project symlink
      file: name={{ nginx.remote_nginx_enable_dir }}/my_site.conf state=absent

    - name: remove nginx avaliable project config file
      file: name={{ nginx.remote_nginx_avail_dir }}/my_site.conf state=absent

    # - name: copy nginx project config file
    #   copy: src={{ local_config_dir }}/nginx.conf dest={{ nginx.remote_nginx_avail_dir }}/my_site.conf

    - name: generate nginx project config file
      template: src={{ local_template_dir }}/nginx.conf.j2 dest={{ nginx.remote_nginx_avail_dir }}/my_site.conf

    - name: create symlink
      file: src={{ nginx.remote_nginx_avail_dir }}/my_site.conf dest={{ nginx.remote_nginx_enable_dir }}/my_site.conf state=link

    - name: restart nginx
      systemd: name=nginx state=restarted
